### ISSUE TITLE
Support for BeforeStep and AfterStep hooks in Cucumber-JVM 3.x.x

### ISSUE THREAD

**Issue by kathyrollo** [damianszczepanik/maven-cucumber-reporting#100]
## Summary
Does not support BeforeStep and AfterStep hooks. AfterStep used to capture/save and capture/embed screenshots.

## Expected Behavior
Embed screenshot into generated HTML using AfterStep hook.

## Current Behavior
Saves screenshots in the specified dir (i.e. `/target/cucumber-screenshots`) but does not embed to the HTML report generated by `maven-cucumber-reporting`. Screenshots embed in Cucumber's native HTML report.

**Native HTML Report:**
Screenshot embedded successfully.
![sshot_1](https://user-images.githubusercontent.com/28589393/41229002-fb8f5d0e-6dac-11e8-9ad4-70782654b120.PNG)

**Maven-Cucumber-Reporting:**
No attachment/embedded image.
![sshot_2](https://user-images.githubusercontent.com/28589393/41229016-04ff89fe-6dad-11e8-9bab-18e0d7551b6e.PNG)

**Saved screenshots:**
![sshot_3](https://user-images.githubusercontent.com/28589393/41229032-10654b08-6dad-11e8-9266-dc9d32bc939e.PNG)

**AfterStep:**

~~~
@AfterStep
public void afterStep() throws Throwable {
	Selenium.captureScreenshot(driver);
	Selenium.embedScreenshot(driver, scenario);
}
~~~

## Context & Motivation
With a [major version release](https://cucumber.io/blog/2018/05/19/announcing-cucumber-jvm-3-0-0), many Cucumber users will likely use AfterStep to capture and embed screenshots.

## Your Environment

* Version used: 3.17.1

**Comment by damianszczepanik** [comment]
Once I get the JSON with the report I can take a look and estimate the time and effort for this feature.

**Comment by kathyrollo** [comment]
Hi @damianszczepanik, thank you for your attention to this ticket. Attached is the generated JSON file using Cucumber-JVM 3.0.2.

[cucumber-report.zip](https://github.com/damianszczepanik/maven-cucumber-reporting/files/2114014/cucumber-report.zip)

Reached the character limit at GitHub when posting JSON code so attached it as ZIP. Let me know if you need other files.

**Comment by damianszczepanik** [comment]
First approach has been implemented. What is left now is to test, calculate status for hooks, probably some small refactor and of course write new tests. Hope to have this in next release bu I can't promise :)

**Comment by chaxshet** [comment]
I've been searching for this feature for 3 days already. I haven't found any clue or answer.

@damianszczepanik , i'll be very thankful once you release your code.

@kathyrollo ,

> @AfterStep
public void afterStep() throws Throwable {
	Selenium.captureScreenshot(driver);
	Selenium.embedScreenshot(driver, scenario);
}

What Selenium you used here? Did you create your own selenium class and capturescreenshot method inside it?

**Comment by kathyrollo** [comment]
Hi @damianszczepanik , as of `3.20.0`, I can confirm `@BeforeStep` and `@AfterStep` hooks in the generated report.

**Step Hooks:**
~~~
@BeforeStep
public void beforeStep() throws Throwable {
	selenium.getScenario().write("This is the before step.");
}

@AfterStep
public void afterStep() throws Throwable {
	if (!Boolean.parseBoolean(PropsLoader.frameworkConf("screenshot.on.fail"))) {
		selenium.embedScreenshot();
	}
}
~~~

**Screenshot:**
![stephooks](https://user-images.githubusercontent.com/28589393/44832159-489cbb80-ac5c-11e8-8431-ad74cbca4f4f.JPG)

Thank you! Closing this ticket.
