### ISSUE TITLE
Classification files could not be read when <outputDirectory> has been changed

### ISSUE THREAD

**Issue by kathyrollo** [damianszczepanik/maven-cucumber-reporting#103]
**Description:**
The classification file I previously used stopped being published in the generated HTML report.

**Version:** 3.18.0

**Actual Result:**
![class_2](https://user-images.githubusercontent.com/28589393/42008759-c07f213a-7ab9-11e8-814b-e5dcc1f5fcd2.png)

**aut.properties:**
![class_1](https://user-images.githubusercontent.com/28589393/42008656-4d523e22-7ab9-11e8-8ae6-8d611d4ddc90.png)

~~~
# Classification file for maven-cucumber-reporting plugin
# See pom.xml for configuration

AngularVersion=0.0.0
AutUiVersion=0.0.0
AutApiVersion=0.0.0
chromeVersion=0.0.0
firefoxVersion=0.0.0
~~~

**pom.xml:**
~~~
<properties>
    <jcucumberng.output>${project.build.directory}/jcucumberng-output</jcucumberng.output>
</properties>

<!-- https://mvnrepository.com/artifact/net.masterthought/maven-cucumber-reporting -->
<plugin>
	<groupId>net.masterthought</groupId>
	<artifactId>maven-cucumber-reporting</artifactId>
	<version>3.18.0</version>
	<executions>
		<execution>
			<id>execution</id>
			<phase>verify</phase>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<projectName>${aut}</projectName>
				<outputDirectory>${jcucumberng.output}</outputDirectory>
				<jsonFiles>
					<param>**/test-report.json</param>
				</jsonFiles>
				<classificationFiles>
					<param>**/aut.properties</param>
				</classificationFiles>
				<parallelTesting>false</parallelTesting>
			</configuration>
		</execution>
	</executions>
</plugin>
~~~

**Comment by kathyrollo** [comment]
I have confirmed this happens when you change the default `<outputDirectory>`.

**Comment by damianszczepanik** [comment]
Yes, this file should be located in same directory where reports are stored. This is by design however now I see that was not perfect design... You can try workaround by using relative path to classification file. Relative to outputDirectory

**Comment by damianszczepanik** [comment]
Hmm, I was able to provide absolute path to the report and it worked

**Comment by kathyrollo** [comment]
Hi @damianszczepanik ,

This works for me now:

![classification_files](https://user-images.githubusercontent.com/28589393/49651804-2be9fe00-fa6b-11e8-971b-db82ae6a882d.png)

```
<classificationFiles>
	<param>**/classifications/*.properties</param>
</classificationFiles>
```
