### ISSUE TITLE
No report is generated when I add this to my POM.xml

### ISSUE THREAD

**Issue by telangn** [damianszczepanik/maven-cucumber-reporting#104]
Can you look over my POM.xml, the plugin is not run when I execute mvn verify. No report is added to my target folder. I've tried many versions. 
```
<build>
<pluginManagement>
<plugin>
	<groupId>net.masterthought</groupId>
	<artifactId>maven-cucumber-reporting</artifactId>
	<version>3.18.0</version>
	<executions>
	    <execution>
	       <id>execution</id>
	       <phase>verify</phase>
	       <goals>
	           <goal>generate</goal>
	        </goals>
	     <configuration>
	           <projectName>CucumberWebGui</projectName>
	           <outputDirectory>${project.build.directory}/cucumber-report- html</outputDirectory>
                   <cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
	     </configuration>
	   </execution>
	</executions>
</plugin>
</pluginManagement>
</build>
```

**Comment by kathyrollo** [comment]
@telangn Check the README of the project for correct `<configuration>` for latest version.

**Comment by telangn** [comment]
@kathyrollo for someone who works on this plugin all the time, that's got to be the worst answer in the history of answers

**Comment by telangn** [comment]
@kathyrollo All I have changed in my project is the pom, as written above. Is there anything else that needs to be done within the project?

**Comment by telangn** [comment]
Removed <PluginManagement>
