### ISSUE TITLE
Missing classificationFiles includes ALL files in target

### ISSUE THREAD

**Issue by KLBonn** [damianszczepanik/maven-cucumber-reporting#106]
When I continue to use only classifications as map in Maven config, then report generation crashes.
Maybe because of #96 ?

POM configuration:

            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>${cucumber-reporting.version}</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <jsonFiles>
                                <jsonFile>cucumber-json-report.json</jsonFile>
                            </jsonFiles>
                            <parallelTesting>false</parallelTesting>
                            <classifications>
                                <betriebssystem>${os.name}</betriebssystem>
                                <ziel-URL>${testSystemURL}</ziel-URL>
                                <browser>${testBrowser}</browser>
                            </classifications>
                            <checkBuildResult>false</checkBuildResult>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

Exception Stacktrace:

> [INFO] About to generate Cucumber report.
> Jul 16, 2018 3:26:23 PM net.masterthought.cucumber.ReportBuilder generateErrorPage
> INFO: Unexpected error
> net.masterthought.cucumber.ValidationException: File 'C:\Users\TQSUserKLJ\Documents\Code\_testautomation_\web-integrationtest\target\cucumber-html-reports\embeddings\embedding_-1373192189.png' doesn't exist or the properties file is invalid!
> 	at net.masterthought.cucumber.ReportParser.processClassificationFile(ReportParser.java:131)
> 	at net.masterthought.cucumber.ReportParser.parseClassificationsFiles(ReportParser.java:115)
> 	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:85)
> 	at net.masterthought.cucumber.CucumberReportGeneratorMojo.execute(CucumberReportGeneratorMojo.java:108)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
> Caused by: org.apache.commons.configuration.ConfigurationException: Unable to load the configuration from the URL file:/C:/Users/TQSUserKLJ/Documents/Code/_testautomation_/web-integrationtest/target/cucumber-html-reports/embeddings/embedding_-1373192189.png
> 	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:332)
> 	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:261)
> 	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
> 	at org.apache.commons.configuration.AbstractFileConfiguration.<init>(AbstractFileConfiguration.java:158)
> 	at org.apache.commons.configuration.PropertiesConfiguration.<init>(PropertiesConfiguration.java:252)
> 	at net.masterthought.cucumber.ReportParser.processClassificationFile(ReportParser.java:123)
> 	... 26 more
> Caused by: org.apache.commons.configuration.ConfigurationRuntimeException: Unable to parse unicode value: ùÙ"]
> 	at org.apache.commons.configuration.PropertiesConfiguration.unescapeJava(PropertiesConfiguration.java:1409)
> 	at org.apache.commons.configuration.PropertiesConfiguration$PropertiesReader.initPropertyValue(PropertiesConfiguration.java:883)
> 	at org.apache.commons.configuration.PropertiesConfiguration$PropertiesReader.parseProperty(PropertiesConfiguration.java:854)
> 	at org.apache.commons.configuration.PropertiesConfiguration$PropertiesReader.nextProperty(PropertiesConfiguration.java:785)
> 	at org.apache.commons.configuration.PropertiesConfigurationLayout.load(PropertiesConfigurationLayout.java:518)
> 	at org.apache.commons.configuration.PropertiesConfiguration.load(PropertiesConfiguration.java:513)
> 	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:395)
> 	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:361)
> 	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:324)
> 	... 31 more
> Caused by: java.lang.NumberFormatException: For input string: "ùÙ"]"
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Integer.parseInt(Integer.java:580)
> 	at org.apache.commons.configuration.PropertiesConfiguration.unescapeJava(PropertiesConfiguration.java:1401)
> 	... 39 more
> 

Debugging into the MOJO reveals:
![image](https://user-images.githubusercontent.com/6554952/42760838-009a177e-890c-11e8-8fc0-5baf8631e734.png)

**Comment by KLBonn** [comment]
Answering myself, a workaround seems to be, to include empty classicationFiles in config, like

                            <classificationFiles>
                            </classificationFiles>

This way report can be created.
But this is not quite user-friendly (even less intuitive) -- would love to see a fix...  :-)

**Comment by damianszczepanik** [comment]
> INFO: Unexpected error
net.masterthought.cucumber.ValidationException: File 'C:\Users\TQSUserKLJ\Documents\Code_testautomation_\web-integrationtest\target\cucumber-html-reports\embeddings\embedding_-1373192189.png' doesn't exist or the properties file is invalid!
I believe this is quite descriptive message.

@bhreinb can you add improvement for that as I guess it scans all files when this property is not set so backwards compatibility is broken now

**Comment by bhreinb** [comment]
i'll submit something in a couple of days to resolve this thread. Thanks.

**Comment by damianszczepanik** [comment]
Problem is fixed
