### ISSUE TITLE
advance HTML report is not generating with Maven-4.0.0

### ISSUE THREAD

**Issue by shah-ishita** [damianszczepanik/maven-cucumber-reporting#107]
Please refer this POM, Do share if anything is missing to generate report. 
Json has been created but advance report is not generating, 

xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>3.18.0</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>testDemo</projectName>  
							<outputDirectory>target/cucumber-reports/advance-report</outputDirectory>
							<cucumberOutput>target/cucumber-reports/CucumberTestReport.json</cucumberOutput>
							<buildNumber>1</buildNumber>
							<parallelTesting>false</parallelTesting>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by damianszczepanik** [comment]
Don't understand the problem

**Comment by shah-ishita** [comment]
Using below configuration, cucumber advance HTML report is not generating, 

`<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>3.18.0</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>testBatchDemo</projectName>  
							<outputDirectory>target/cucumber-reports/advance-reports</outputDirectory>
							<cucumberOutput>target/cucumber-reports/CucumberTestReport.json</cucumberOutput>
							<buildNumber>1</buildNumber>
							<parallelTesting>false</parallelTesting>
						</configuration>
					</execution>
				</executions>
			</plugin>`

**Comment by damianszczepanik** [comment]
This is sample configuration https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/README.md
