### ISSUE TITLE
Support for parametrised build number

### ISSUE THREAD

**Issue by alborworld** [damianszczepanik/maven-cucumber-reporting#11]
Hi, I have noticed that the build number is always set to one. Looking at the code, it's hardcoded.

It's seems to be pretty straightforward to add an optional parameter to specify it - that could be useful for instance in the case the CI tool (e.g. Jenkins, TeamCity, etc.) provides the build number, that we want to see in the report.

@kingsleyh I have implemented the changes. Could you have a look?

**Comment by woodybrood** [comment]
Was this ever used/released? I see a buildNumber parameter in the code, but when I try to use it, the build number never changes.

    <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>0.0.6</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>test</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>cfw</projectName>
                            <outputDirectory>${cucumberReportDestination}/cucumber-html-reports</outputDirectory>
                            <cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
                            <enableFlashCharts>false</enableFlashCharts>
                            <buildNumber>${bambooBuildNumber}</buildNumber>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by damianszczepanik** [comment]
Released, time ago
