### ISSUE TITLE
Configuration issue when trying to generate cucumber reports without Maven help

### ISSUE THREAD

**Issue by Karthik3012** [damianszczepanik/maven-cucumber-reporting#112]
Hi,

I'm trying to generate pretty cucumber html reports without Maven POM.xml file. As maven will not work in my client network. So I'm trying to implement in normal java project with TestNG framework. I'm using the following code to generate the report. But I'm getting a configuration failure message at creating the reportbuilder object.

		File reportOutputDirectory = new File("target");
		List<String> jsonFiles = new ArrayList<>();
		jsonFiles.add("cucumber.json");

		String buildNumber = "1";
		String projectName = "cucumberProject";
		boolean runWithJenkins = false;
		boolean parallelTesting = false;

		Configuration configuration = new Configuration(reportOutputDirectory, projectName);
		// optional configuration - check javadoc
		configuration.setRunWithJenkins(runWithJenkins);
		configuration.setBuildNumber(buildNumber);
		// addidtional metadata presented on main page
		configuration.addClassifications("Platform", "Windows");
		configuration.addClassifications("Browser", "Firefox");
		configuration.addClassifications("Branch", "release/1.0");

		**ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);**
		Reportable result = reportBuilder.generateReports();

Can you please help me in this?

**Comment by damianszczepanik** [comment]
What failure?
