### ISSUE TITLE
BUILD FAILURE even with <testFailureIgnore> set to true

### ISSUE THREAD

**Issue by kathyrollo** [damianszczepanik/maven-cucumber-reporting#116]
## Summary
Results to BUILD FAILURE with `<testFailureIgnore>true</testFailureIgnore>` when assertion fails.

## Expected Behavior
To return BUILD SUCCESS even with failed assertions or a flag that can be set.

## Current Behavior
I deliberately failed an assertion in one `@Then` stepdef and `maven-cucumber-reporting` appears to "override" the `<testFailureIgnore>` in `maven-surefire-plugin` and fails the build. Other exceptions return BUILD SUCCESS. Only assertion failures return BUILD FAILURE. The report **_is_** generated properly, I just prefer it not to fail the build.

**pom.xml:**
~~~
<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>2.22.0</version>
	<configuration>
		<testFailureIgnore>true</testFailureIgnore>
		<includes>
			<include>**/RunCukesTest.java</include>
		</includes>
		<reportsDirectory>${project.build.directory}/test-output/${timestamp}</reportsDirectory>
	</configuration>
</plugin>
<!-- https://mvnrepository.com/artifact/net.masterthought/maven-cucumber-reporting -->
<plugin>
	<groupId>net.masterthought</groupId>
	<artifactId>maven-cucumber-reporting</artifactId>
	<version>3.20.0</version>
	<executions>
		<execution>
			<id>execution</id>
			<phase>verify</phase>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<projectName>${app.name}</projectName>
				<outputDirectory>${project.build.directory}</outputDirectory>
				<jsonFiles>
					<param>**/cucumber-report.json</param>
				</jsonFiles>
				<classificationFiles>
					<param>**/classifications/*.properties</param>
				</classificationFiles>
				<parallelTesting>false</parallelTesting>
			</configuration>
		</execution>
	</executions>
</plugin>
~~~

**Output:**
~~~
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   expected:<...Do - Balance Project[]"> but was:<...Do - Balance Project[or]">
[INFO]
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[ERROR] There are test failures.

Please refer to D:\dev\automation-testing\java\jCucumberNG-Framework\target\test-output\20180902T041532Z for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ jcucumberng-framework ---
[INFO] Building jar: D:\dev\automation-testing\java\jCucumberNG-Framework\target\jcucumberng-framework-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-cucumber-reporting:3.20.0:generate (execution) @ jcucumberng-framework ---
[INFO] About to generate Cucumber report.
Sep 02, 2018 12:16:12 PM net.masterthought.cucumber.ReportParser parseJsonFiles
INFO: File 'D:\dev\automation-testing\java\jCucumberNG-Framework\target\cucumber-report.json' contains 2 features
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.454 s
[INFO] Finished at: 2018-09-02T12:16:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.masterthought:maven-cucumber-reporting:3.20.0:generate (execution) on project jcucumberng-framework: Error Found:: BUILD FAILED - Check Report For Details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
~~~

**Screenshot:**
![failed_assert](https://user-images.githubusercontent.com/28589393/44952267-4c278100-aeae-11e8-9de8-6fd7d903c08e.png)

## Possible Solution
~~~
<configuration>
	...
	<jsonFiles>
		<param>**/cucumber-report.json</param>
	</jsonFiles>
	<classificationFiles>
		<param>**/classifications/*.properties</param>
	</classificationFiles>
	<parallelTesting>false</parallelTesting>
	<buildSuccessOnTestFailure>true</buildSuccessOnTestFailure>
</configuration>
~~~
`<buildSuccessOnTestFailure>`
- true - returns BUILD SUCCESS even with failed assertion (honors `<testFailureIgnore>true</testFailureIgnore>`)
- false - returns BUILD FAILURE with failed assertion (same as current behavior)

## Context & Motivation
The native Cucumber HTML report proceeds to BUILD SUCCESS with failed assertion using `<testFailureIgnore>true</testFailureIgnore>`.

## Your Environment
* Version used: 3.20.0

**Comment by kathyrollo** [comment]
I found the exact feature I was looking for at Issue #70, particularly PR #74.

Below would make a fine addition to the README.md. Thanks!
~~~
<configuration>
	...
	<parallelTesting>false</parallelTesting>
	<!-- Set true to fail build on test failures -->
	<checkBuildResult>false</checkBuildResult>
</configuration>
~~~

**Comment by damianszczepanik** [comment]
@kathyrollo This is open source project - I will be happy to accept PR about this

**Comment by ozturktx** [comment]
same issue here, still shows build failure even though added <checkBuildResult>false</checkBuildResult>

**Comment by damianszczepanik** [comment]
open new issue with details

**Comment by orhansubay** [comment]
Hi,

I have a problem with Cucumber HTML reporting. When I click Maven, Lifecycle and Verify, the system produces an error. "Failed to execute goal net.masterthought:maven-cucumber-reporting:5.0.0:generate (execution) on project cucumber-selenium: Error Found:"

My pom.xml is like below and it stucks at groupId>net.masterthought</groupId> line.

   <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <includes>
                        <include>**/*Runner.java</include>
                        <include>**/*FailedTestRunner.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>5.0.0</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>Cucumber HTML Reports</projectName>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <inputDirectory>${project.build.directory}</inputDirectory>
                            <jsonFiles>
                                <param>*/cucumber.json</param>
                            </jsonFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins> 

May anyone help me?
