### ISSUE TITLE
New functionality ReduceMethod.MERGE_FEATURES_BY_ID not available 

### ISSUE THREAD

**Issue by KateMk** [damianszczepanik/maven-cucumber-reporting#120]
Hi , 
Is it possible use this functionality as plugin configuration ?
https://github.com/damianszczepanik/cucumber-reporting/pull/763

**Comment by damianszczepanik** [comment]
Yes, with new version that has been released now

**Comment by damianszczepanik** [comment]
No, this is possible with the plugin, but not yet with the maven

**Comment by KateMk** [comment]
Thanks for ur answer. Just to clarify - if I use jenkins plugin I will be able to merge scenarios by feature _id ? And one final and so important for me qustion - do u have any plan/timeline to implement it for maven ? 
Thanks in advance

**Comment by damianszczepanik** [comment]
Wait for next release #125
