### ISSUE TITLE
Exception in thread "main" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by PW999** [damianszczepanik/maven-cucumber-reporting#121]
We get the following error when running the maven-cucumber-reporting plugin

> [INFO] 
> [INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ XXX-service ---
> [INFO] Building jar: /workspace/workspace/XXX-VYK24ODPLNROGVDV73XO2HAEIFSEMK3C57JSNZ2XGFOYLXJY4UKA/target/XXX-service-2.0.0-BUDDI-SNAPSHOT.jar
> [INFO] 
> [INFO] --- spring-boot-maven-plugin:1.5.16.RELEASE:repackage (default) @ XXX-service ---
> 
> [INFO] 
> [INFO] --- maven-cucumber-reporting:3.20.0:generate (execution) @ XXX-service ---
> 
> [INFO] About to generate Cucumber report.
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 03:15 min
> [INFO] Finished at: 2018-10-15T08:23:11Z
> [INFO] Final Memory: 78M/1383M
> [INFO] ------------------------------------------------------------------------
> ---------------------------------------------------
> constituent[0]: file:/opt/maven/apache-maven-3.5.2/conf/logging/
> constituent[1]: file:/opt/maven/apache-maven-3.5.2/lib/aopalliance-1.0.jar
> constituent[2]: file:/opt/maven/apache-maven-3.5.2/lib/cdi-api-1.0.jar
> constituent[3]: file:/opt/maven/apache-maven-3.5.2/lib/commons-cli-1.4.jar
> constituent[4]: file:/opt/maven/apache-maven-3.5.2/lib/commons-io-2.5.jar
> constituent[5]: file:/opt/maven/apache-maven-3.5.2/lib/commons-lang3-3.5.jar
> constituent[6]: file:/opt/maven/apache-maven-3.5.2/lib/guava-20.0.jar
> constituent[7]: file:/opt/maven/apache-maven-3.5.2/lib/guice-4.0-no_aop.jar
> constituent[8]: file:/opt/maven/apache-maven-3.5.2/lib/jansi-1.16.jar
> constituent[9]: file:/opt/maven/apache-maven-3.5.2/lib/javax.inject-1.jar
> constituent[10]: file:/opt/maven/apache-maven-3.5.2/lib/jcl-over-slf4j-1.7.25.jar
> constituent[11]: file:/opt/maven/apache-maven-3.5.2/lib/jsr250-api-1.0.jar
> constituent[12]: file:/opt/maven/apache-maven-3.5.2/lib/maven-artifact-3.5.2.jar
> constituent[13]: file:/opt/maven/apache-maven-3.5.2/lib/maven-builder-support-3.5.2.jar
> constituent[14]: file:/opt/maven/apache-maven-3.5.2/lib/maven-compat-3.5.2.jar
> constituent[15]: file:/opt/maven/apache-maven-3.5.2/lib/maven-core-3.5.2.jar
> constituent[16]: file:/opt/maven/apache-maven-3.5.2/lib/maven-embedder-3.5.2.jar
> constituent[17]: file:/opt/maven/apache-maven-3.5.2/lib/maven-model-3.5.2.jar
> constituent[18]: file:/opt/maven/apache-maven-3.5.2/lib/maven-model-builder-3.5.2.jar
> constituent[19]: file:/opt/maven/apache-maven-3.5.2/lib/maven-plugin-api-3.5.2.jar
> constituent[20]: file:/opt/maven/apache-maven-3.5.2/lib/maven-repository-metadata-3.5.2.jar
> constituent[21]: file:/opt/maven/apache-maven-3.5.2/lib/maven-resolver-api-1.1.0.jar
> constituent[22]: file:/opt/maven/apache-maven-3.5.2/lib/maven-resolver-connector-basic-1.1.0.jar
> constituent[23]: file:/opt/maven/apache-maven-3.5.2/lib/maven-resolver-impl-1.1.0.jar
> constituent[24]: file:/opt/maven/apache-maven-3.5.2/lib/maven-resolver-provider-3.5.2.jar
> constituent[25]: file:/opt/maven/apache-maven-3.5.2/lib/maven-resolver-spi-1.1.0.jar
> constituent[26]: file:/opt/maven/apache-maven-3.5.2/lib/maven-resolver-transport-wagon-1.1.0.jar
> constituent[27]: file:/opt/maven/apache-maven-3.5.2/lib/maven-resolver-util-1.1.0.jar
> constituent[28]: file:/opt/maven/apache-maven-3.5.2/lib/maven-settings-3.5.2.jar
> constituent[29]: file:/opt/maven/apache-maven-3.5.2/lib/maven-settings-builder-3.5.2.jar
> constituent[30]: file:/opt/maven/apache-maven-3.5.2/lib/maven-shared-utils-3.1.0.jar
> constituent[31]: file:/opt/maven/apache-maven-3.5.2/lib/maven-slf4j-provider-3.5.2.jar
> constituent[32]: file:/opt/maven/apache-maven-3.5.2/lib/org.eclipse.sisu.inject-0.3.3.jar
> constituent[33]: file:/opt/maven/apache-maven-3.5.2/lib/org.eclipse.sisu.plexus-0.3.3.jar
> constituent[34]: file:/opt/maven/apache-maven-3.5.2/lib/plexus-cipher-1.7.jar
> constituent[35]: file:/opt/maven/apache-maven-3.5.2/lib/plexus-component-annotations-1.7.1.jar
> constituent[36]: file:/opt/maven/apache-maven-3.5.2/lib/plexus-interpolation-1.24.jar
> constituent[37]: file:/opt/maven/apache-maven-3.5.2/lib/plexus-sec-dispatcher-1.4.jar
> constituent[38]: file:/opt/maven/apache-maven-3.5.2/lib/plexus-utils-3.1.0.jar
> constituent[39]: file:/opt/maven/apache-maven-3.5.2/lib/slf4j-api-1.7.25.jar
> constituent[40]: file:/opt/maven/apache-maven-3.5.2/lib/wagon-file-2.12.jar
> constituent[41]: file:/opt/maven/apache-maven-3.5.2/lib/wagon-http-2.12-shaded.jar
> constituent[42]: file:/opt/maven/apache-maven-3.5.2/lib/wagon-provider-api-2.12.jar
> ---------------------------------------------------
> Exception in thread "main" java.lang.StackOverflowError
> 	at java.util.regex.Pattern$Ctype.isSatisfiedBy(Pattern.java:3914)
> 	at java.util.regex.Pattern$CharProperty$1.isSatisfiedBy(Pattern.java:3773)
> 	at java.util.regex.Pattern$6.isSatisfiedBy(Pattern.java:5263)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3778)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
> 	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
> 	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
> 	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
> 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
> 	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
> 	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)

The maven configuration for the plugin is
```
			<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>3.20.0</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>

					</execution>
				</executions>
				<configuration>
					<projectName>meter-service</projectName>
					<!-- output directory for the generated report -->
					<outputDirectory>${project.build.directory}/maven-cucumber-report</outputDirectory>
					<!-- optional, defaults to outputDirectory if not specified -->
					<inputDirectory>${project.build.directory}/</inputDirectory>
					<jsonFiles>
						<!-- supports wildcard or name pattern -->
						<param>**/*cucumber.json</param>
					</jsonFiles>
					<parallelTesting>false</parallelTesting>
				</configuration>
			</plugin>
```

At first, this issue appeared when running a Sonarqube report (after a mvn clean deploy finished sucessfully). I can reproduce this error by running 'mvn verify' instead of 'mvn clean deploy' (without cleaning the workspace).
When I look in the target folder, the cucumber json reports exist.

**Comment by damianszczepanik** [comment]
The most important information about stacktrace is missing

**Comment by it-uragan** [comment]
I had the same issue and stacktrace was very similar, there was no another information

[INFO] --- maven-cucumber-reporting:3.20.0:generate (execution) @ nasdaq-wcst-cs-qa-authomation ---
[INFO] About to generate Cucumber report.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:34 min
[INFO] Finished at: 2018-11-29T17:23:01+02:00
[INFO] Final Memory: 43M/455M
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/aether-api-1.0.2.v20150114.jar
constituent[1]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/aether-connector-basic-1.0.2.v20150114.jar
constituent[2]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/aether-impl-1.0.2.v20150114.jar
constituent[3]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/aether-spi-1.0.2.v20150114.jar
constituent[4]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/aether-transport-wagon-1.0.2.v20150114.jar
constituent[5]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/aether-util-1.0.2.v20150114.jar
constituent[6]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/aopalliance-1.0.jar
constituent[7]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/cdi-api-1.0.jar
constituent[8]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/commons-cli-1.2.jar
constituent[9]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/commons-io-2.2.jar
constituent[10]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/commons-lang-2.6.jar
constituent[11]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/commons-lang3-3.4.jar
constituent[12]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/guava-18.0.jar
constituent[13]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/guice-4.0-no_aop.jar
constituent[14]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/javax.inject-1.jar
constituent[15]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/jsoup-1.7.2.jar
constituent[16]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/jsr250-api-1.0.jar
constituent[17]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-aether-provider-3.3.9.jar
constituent[18]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-artifact-3.3.9.jar
constituent[19]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-builder-support-3.3.9.jar
constituent[20]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-compat-3.3.9.jar
constituent[21]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-core-3.3.9.jar
constituent[22]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-embedder-3.3.9.jar
constituent[23]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-model-3.3.9.jar
constituent[24]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-model-builder-3.3.9.jar
constituent[25]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-plugin-api-3.3.9.jar
constituent[26]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-repository-metadata-3.3.9.jar
constituent[27]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-settings-3.3.9.jar
constituent[28]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/maven-settings-builder-3.3.9.jar
constituent[29]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/org.eclipse.sisu.inject-0.3.2.jar
constituent[30]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/org.eclipse.sisu.plexus-0.3.2.jar
constituent[31]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/plexus-cipher-1.7.jar
constituent[32]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/plexus-component-annotations-1.6.jar
constituent[33]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/plexus-interpolation-1.21.jar
constituent[34]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/plexus-sec-dispatcher-1.3.jar
constituent[35]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/plexus-utils-3.0.22.jar
constituent[36]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/slf4j-api-1.7.5.jar
constituent[37]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/slf4j-simple-1.7.5.jar
constituent[38]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/wagon-file-2.10.jar
constituent[39]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/wagon-http-2.10-shaded.jar
constituent[40]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/wagon-http-shared-2.10.jar
constituent[41]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/lib/wagon-provider-api-2.10.jar
constituent[42]: file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.2.5/plugins/maven/lib/maven3/conf/logging/
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
	at java.util.regex.Pattern$CharProperty$1.isSatisfiedBy(Pattern.java:3771)
	at java.util.regex.Pattern$6.isSatisfiedBy(Pattern.java:5261)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3776)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
...
