### ISSUE TITLE
when running multiple feature files only one report open (from overview-features.html) in browser as other shows as file not found

### ISSUE THREAD

**Issue by hi-Kedarnath** [damianszczepanik/maven-cucumber-reporting#128]
@damianszczepanik 

I am using eclipse/command line to run the feature files using mvn install/verify. I am not using Jenkins.

When multiple feature files were run, only able to view one report in browser and other files shows as File Not Found error. This is due to path/location of other report files (.html) are stored in symbol-ink and the hyperlink from the overview.html page expect actual path/link instead of symbolink.

Example - I ran 3 feature files and the html created as below. Also mentioning the location stored (as shown in file properties) for each file.

File Name - report-feature_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_1-feature.html
Location of File (as shown in file properties)- F:\eclipse-dsl-luna-SR2-win32-x86_64\parallel_feature\artifacts\12Nov2018-120327PM-UTC\report-12Nov2018-120327PM-UTC\cucumber-html-reports

File Name - report-feature_2_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_3-feature.html
Location of File (as shown in file properties)- F:\ECLIPS1\PARALL1\ARTIFA1\123CD81\REPORT1\CUCUMB1

File Name - report-feature_1_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_2-feature.html
Location of File (as shown in file properties) - F:\ECLIPS1\PARALL1\ARTIFA1\123CD81\REPORT1\CUCUMB1

As the location are stored as symbol-link so feature file 2 and 3 can not be opened from browser as the link from overview-features.html page expect path like
file:///F:/eclipse-dsl-luna-SR2-win32-x86_64/parallel_feature/artifacts/12Nov2018-120327PM-UTC/report-12Nov2018-120327PM-UTC/cucumber-html-reports/report-feature_1_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_2-feature.html

file:///F:/eclipse-dsl-luna-SR2-win32-x86_64/parallel_feature/artifacts/12Nov2018-120327PM-UTC/report-12Nov2018-120327PM-UTC/cucumber-html-reports/report-feature_2_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_3-feature.html

Is this due to some configuration issue from my end or it has something to do with existing code. Please let me know.

My pom.xml looks as below.

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.rebaca</groupId>
  <artifactId>parallel_feature_files</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  	<packaging>jar</packaging>

	<name>parallel_testing</name>
	<url>http://maven.apache.org</url>

	<properties>
		<maven.build.timestamp.format>ddMMMyyyy-HHmmssaa-z</maven.build.timestamp.format>
	</properties>

	<repositories>
		<repository>
			<id>repo.bodar.com</id>
			<url>http://repo.bodar.com</url>
		</repository>
		<repository>
			<id>Eclipse</id>
			<url>https://repo.eclipse.org/content/groups/releases/</url>
		</repository>
	</repositories>
	<dependencies>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin</artifactId>
			<version>2.12.2</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin-jvm-deps</artifactId>
			<version>1.0.3</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>3.0.1</version>
		</dependency>

		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java8</artifactId>
			<version>1.2.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode.totallylazy</groupId>
			<artifactId>totallylazy</artifactId>
			<version>1.81</version>
		</dependency>
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>4.2.1</version>
		</dependency>
		
	
		
		<dependency>
		    <groupId>com.github.temyers</groupId>
		    <artifactId>cucumber-jvm-parallel-plugin</artifactId>
		    <version>2.2.0</version>
		</dependency>
		
		

	</dependencies>
	<build>
		<defaultGoal>install</defaultGoal>
		<directory>${basedir}/target</directory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
			    <groupId>com.github.temyers</groupId>
			    <artifactId>cucumber-jvm-parallel-plugin</artifactId>
			    <version>2.2.0</version>
			    <executions>
			        <execution>
			            <id>generateRunners</id>
			            <phase>validate</phase>
			            <goals>
			                <goal>generateRunners</goal>
			            </goals>
			            <configuration>
			                <glue>parallel_feature_files</glue>
			                <featuresDirectory>src/test/resources/com</featuresDirectory>
			                <cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
			            </configuration>
			        </execution>
			    </executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<skip>false</skip>
					<forkCount>10</forkCount>
					<reuseForks>false</reuseForks>
					
					<reportFormat>plain</reportFormat>
					<runOrder>alphabetical</runOrder>
					<junitArtifactName>junit:junit</junitArtifactName>
					<encoding>UTF-8</encoding>
					<inputEncoding>UTF-8</inputEncoding>
					<outputEncoding>UTF-8</outputEncoding>
					<includes>
			            <include>**/Parallel*IT.class</include>
			        </includes>
					<testFailureIgnore>true</testFailureIgnore>
				</configuration>
			</plugin>
			<plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>4.2.1</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>Parallel reporting</projectName>
                            <skip>false</skip>
                            <outputDirectory>${basedir}/artifacts/${maven.build.timestamp}/report-${maven.build.timestamp}</outputDirectory>
                            <inputDirectory>${project.build.directory}/cucumber-parallel</inputDirectory>
                            <jsonFiles>
                                <param>**/*.json</param>
                            </jsonFiles>
                            <parallelTesting>true</parallelTesting>
                            <enableFlashCharts>true</enableFlashCharts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>
</project>

My Runner class is as below

@RunWith(Cucumber.class)
@CucumberOptions(
		features = { "./" }, 
		glue={"parallel_feature_files/"},
		plugin={"pretty", "json:target/cucumber-parallel/cucumber.json"},
		tags={"~@ignore"},
		strict = true
		)

public class CucumberRunnerTest {

}

Thanks in advance
Kedar

**Comment by damianszczepanik** [comment]
This could happen after upgrading to next major version such as 4.0.0
