### ISSUE TITLE
Mvn verify

### ISSUE THREAD

**Issue by vanatomas** [damianszczepanik/maven-cucumber-reporting#130]
@damianszczepanik   Is there a way to change from mvn verify to something else?
Reason is that in the build, we have mvn install and then mvn test verify.
So, while running mvn test verify works as expected.
But puting mvn install before, it fails on section
About to generate Cucumber report
Unexpected error
net.masterthought,cucumber.ValidationException: No report file was added

**Comment by damianszczepanik** [comment]
This plugin does not limit this. Read mvn documentation

**Comment by vanatomas** [comment]
@damianszczepanik why then I get error on mvn install specifically for this report?

**Comment by vikrant-lh** [comment]
I also had same issue. So as an alternative I am using skip tag with
${maven.test.skip} paramter. mvn clean install -Dmaven.test.skip=true
@damianszczepanik It would be great if some flexibility is provided within the plugin to skip report generation in mvn install
