### ISSUE TITLE
skipEmptyJSONFiles missing @parameter annotation

### ISSUE THREAD

**Issue by fularac** [damianszczepanik/maven-cucumber-reporting#136]
skipEmptyJSONFiles added in #135 is not able to be set in plugin configuration. 

I've tested adding the @parameter notation locally and configuration is now possible.

**Comment by damianszczepanik** [comment]
Would you like to prepare PR with fix?

**Comment by damianszczepanik** [comment]
Would you like to prepare PR with fix?
