### ISSUE TITLE
CORS issue when deploying site to Sonatype Nexus

### ISSUE THREAD

**Issue by melloware** [damianszczepanik/maven-cucumber-reporting#149]
Amazing job on this plugin!  I am just having one issue with the latest version.

You can read my comment here: https://issues.sonatype.org/browse/NEXUS-12710

I read about the problem here: https://stackoverflow.com/questions/26125030/font-awesome-icons-not-showing-in-chrome-a-maxcdn-related-cross-origin-resource

I am wondering if there is anything that can be done in the HTML generation of if this is truly a Sonatype Nexus issue?

**Comment by damianszczepanik** [comment]
Icons are displayed properly. Could not reproduce the problem

**Comment by melloware** [comment]
Yeah I think its related to the Nexus issue https://issues.sonatype.org/browse/NEXUS-12710

the site works fine if I just open the local files in my browser.
