### ISSUE TITLE
totallylazy v991 no longer available

### ISSUE THREAD

**Issue by jlorenzen** [damianszczepanik/maven-cucumber-reporting#15]
Currently the maven-cucumber-reporting-mojo depends on totallylazy version 991 (https://github.com/masterthought/maven-cucumber-reporting-mojo/blob/master/pom.xml#L130). This dependency is no longer available on the repo http://repo.bodar.com. You should update this to version 1077 as the project README indicates.

**Comment by jlorenzen** [comment]
@kingsleyh any update on this?

**Comment by kingsleyh** [comment]
Not yet sorry - possibly next week

**Comment by damianszczepanik** [comment]
Does not happen in recent releases
