### ISSUE TITLE
Showing trends with previous json reports like jenkins plugin

### ISSUE THREAD

**Issue by manjeet88** [damianszczepanik/maven-cucumber-reporting#150]
Is there a way to generate a report and show trends if we add multiple json files from previous builds, current maven report just generates the reports for current build ?

**Comment by damianszczepanik** [comment]
Yes, you can have trends chart like https://github.com/damianszczepanik/cucumber-reporting

**Comment by manjeet88** [comment]
@damianszczepanik  - I was referring to maven plugin, can you point me to the configuration in maven plugin to do the same.

**Comment by damianszczepanik** [comment]
Looks like the support is missing here

**Comment by manjeet88** [comment]
@damianszczepanik - do you think that support can be done quicky, is there a way to cucumber jenkins plugin to generate report in jenkins agent instead of master, then we can use the reports generated in jenkins workspace and publish it to an external repository

**Comment by damianszczepanik** [comment]
Jenkins plugin works fine now and I hope this plugin will be supported quickly as well. However for the trends you need to point to the location where the file with history will be saved and for sure it can't be targer/ directory

**Comment by manjeet88** [comment]
@damianszczepanik - yes agreed, we do store the cucumber report json files for each build in a separate scp repository, we can download all the files in workspace and load the json files and generate report using maven plugin. I referred to Jenkins plugin to give option to select where to generate the report instead of by default generating it to master, as that will allow us to just use the already generated report in jenkins workspace and publishing it to scp repository. As we don't keep much of the build histories in jenkins, that will allow us to show the trend of report to a different web host

**Comment by damianszczepanik** [comment]
Wait for next release

**Comment by manjeet88** [comment]
@damianszczepanik - Can you update when will be the next release for this plugin ?
