### ISSUE TITLE
The parameters 'jsonFiles' for goal net.masterthought:maven-cucumber-reporting:4.6.0:generate are missing or invalid

### ISSUE THREAD

**Issue by pnakhat** [damianszczepanik/maven-cucumber-reporting#151]
I have the parameter added but keeps complaining 

< <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>${masterThougt.version}</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>

                            <configuration>
                                <projectName>cucumber-jvm-example</projectName>
                                <skip>false</skip>
                                <outputDirectory>${project.build.directory}/site</outputDirectory>
                                <inputDirectory>${project.build.directory}/jsonReports</inputDirectory>
                                <jsonFiles>
                                    <param>>**/*.json</param>
                                </jsonFiles>

                                <checkBuildResult>false</checkBuildResult>

                            </configuration>
                    </execution>
                </executions>
            </plugin>>

**Comment by damianszczepanik** [comment]
I don't have much experiences with maven configuration but if you find solution let us know

**Comment by marcellemuniz** [comment]
I had the same problem and it worked using the configuration below. I hope it will help you.
 <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>MyProjectName</projectName>  
                            <outputDirectory>target/cucumber-reports/advanced-reports</outputDirectory>
                            <cucumberOutput>target/cucumber-reports/CucumberTestReport.json</cucumberOutput>
                            <buildNumber>1</buildNumber>
                            <parallelTesting>false</parallelTesting>
                            <skip>false</skip>
                            <inputDirectory>${project.build.directory}/cucumber-reports</inputDirectory>
                            <jsonFiles>
                                
                                <param>**/*.json</param>
                            </jsonFiles>
                            
                            <classificationDirectory>${project.build.directory}/cucumber-reports</classificationDirectory>
                            <classificationFiles>
                                
                                <param>sample.properties</param>
                                <param>other.properties</param>
                            </classificationFiles>
                            <parallelTesting>false</parallelTesting>
                            
                            <checkBuildResult>false</checkBuildResult>
                        </configuration>
                    </execution>
                </executions>

**Comment by damianszczepanik** [comment]
And what is the error?

**Comment by techborn** [comment]
Firstly, there is an extra > in the params node.
Secondly, there should not be a params node, it needs to be a singluar of the parent.
The naming is a bit of a misnomer.
The jsonFiles node should look like:
```xml
<jsonFiles>
    <jsonFile>**/*.json<jsonFile>
</jsonFiles>
```

**Comment by damianszczepanik** [comment]
OK, thanks

**Comment by Cilke** [comment]
@marcellemuniz This fix my issues thanks a lot!!!

**Comment by Cilke** [comment]
@damianszczepanik thanks for sharing it, we love this great report!

**Comment by alexDunga3pg** [comment]
Im running this with version 5.5.0 and I'm still getting a warning. 
       <plugin>
            <groupId>net.masterthought</groupId>
            <artifactId>maven-cucumber-reporting</artifactId>
            <version>${masterthought-version}</version>
            <executions>
                <execution>
                    <id>execution</id>
                    <phase>verify</phase>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                    <configuration>
                        <projectName>cucumber-jvm-example</projectName>
                        
                        <skip>false</skip>
                        
                        <outputDirectory>${project.build.directory}</outputDirectory>
                        
                        <inputDirectory>${project.build.directory}/cucumber-report</inputDirectory>
                        <jsonFiles>
                            <param>**/*.json</param>
                        </jsonFiles>
                        
                        <classificationDirectory>${project.build.directory}/classifications</classificationDirectory>
                        <classificationFiles>
                            
                            <param>sample.properties</param>
                            <param>other.properties</param>
                        </classificationFiles>
                        <parallelTesting>false</parallelTesting>
                        
                        <mergeFeaturesById>false</mergeFeaturesById>
                        
                        <mergeFeaturesWithRetest>false</mergeFeaturesWithRetest>
                        
                        <checkBuildResult>false</checkBuildResult>
                    </configuration>
                </execution>
            </executions>
        </plugin>

any thoughts?

**Comment by alexDunga3pg** [comment]
I'm running this with version 5.5.0 and it still getting the error. 
Any thoughts? 
[pom.txt](https://github.com/damianszczepanik/maven-cucumber-reporting/files/6479098/pom.txt)

**Comment by alexDunga3pg** [comment]
so if anyone is still having an issue i thing I found a way. the <configuration> can be put outside the <executions>
it will be global but it worked for me with 5.5.0

from cluecumber :)
<executions>
    <execution>
        <id>report</id>
        <phase>post-integration-test</phase>
        <goals>
            <goal>reporting</goal>
        </goals>
        <configuration>
            
        </configuration>
    </execution>
</executions>
<configuration>
    
</configuration>

the the configuration inside the execution block works only for that block



[hack.txt](https://github.com/damianszczepanik/maven-cucumber-reporting/files/6479232/hack.txt)
