### ISSUE TITLE
BUILD FAILURE even with <testFailureIgnore> set to true and <checkBuildResult> set to false

### ISSUE THREAD

**Issue by ozturktx** [damianszczepanik/maven-cucumber-reporting#158]
--------------------Plugins-------------------

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                   <testFailureIgnore>true</testFailureIgnore>
 </configuration>
            </plugin>
<plugin>
                        <groupId>net.masterthought</groupId>
                        <artifactId>maven-cucumber-reporting</artifactId>
                        <version>4.8.0</version>
                        <executions>
                            <execution>
                                <id>execution</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <projectName>cucumber-jvm-example</projectName>
                                    <outputDirectory>${project.build.directory}/cucumber-pretty-reports
                                    </outputDirectory>
                                    <inputDirectory>${project.build.directory}</inputDirectory>
                                    <jsonFiles>
                                        <param>**/cucumber.json</param>
                                    </jsonFiles>
                                    <classificationFiles>
                                        <param>sample.properties</param>
                                        <param>other.properties</param>
                                    </classificationFiles>
                                    <checkBuildResult>false</checkBuildResult>

------------------------------------------------------------------------------------------
Output
------------------------------------
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-cucumber-reporting:4.8.0:generate (execution) @ mattermanagement-web ---
[INFO] About to generate Cucumber report.
Jul 18, 2019 3:21:33 PM net.masterthought.cucumber.ReportParser parseJsonFiles
INFO: File 'C:\work\projects\Galileo\mattermanagement-web\target\cucumber.json' contains 1 features
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ mattermanagement-web ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:39 min
[INFO] Finished at: 2019-07-18T15:21:33-05:00
[INFO] Final Memory: 86M/828M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.1:verify (default) on project mattermanagement-web: There are test failures.
----------------------------------------------------------------------------------------------------------
Can't figure it out why it shows build failure for a specific test failure.

**Comment by damianszczepanik** [comment]
and the maven configuration?

**Comment by ozturktx** [comment]
not sure what u mean with maven configuration? that's how I run it 
mvn clean verify -P integration -D it.test=Runner

**Comment by damianszczepanik** [comment]
pom.xml file

**Comment by ozturktx** [comment]
![image](https://user-images.githubusercontent.com/40250404/61544738-aa4c4c80-aa0b-11e9-9b49-ae41e472a8a1.png)

**Comment by RomaSha2009** [comment]
Try to set a lower version of maven-cucumber-report. In my case v3.10.0 resolved the issue.

**Comment by damianszczepanik** [comment]
Well, based on this I think the problem is with configuration failsafe plugin and not the cucumber itself
