### ISSUE TITLE
Provide a complete example with at least two features 

### ISSUE THREAD

**Issue by Watcher24** [damianszczepanik/maven-cucumber-reporting#162]
Please provide a fully fledged complete example with at least two (!) features - each of the features with a feature file, a Test-class with the @CucumberOptions and the step-def); plus the pom file.

This plugin comes with a bunch of configuration params - which are not all clear what they are used for.

**Comment by damianszczepanik** [comment]
I recommend to go through https://github.com/damianszczepanik/cucumber-reporting
