### ISSUE TITLE
Report shows duplicate features as a result of rerun of failed scenarios

### ISSUE THREAD

**Issue by neo81-83** [damianszczepanik/maven-cucumber-reporting#169]
Hello My Friend,

I am using your plugin for generating html report, my execution produces 2 JSON files one from the normal cucumber class and the other from the rerun failed cucumber class. As suggested in your documentation I have supplied the path in pom.xml but when the report is generated the scenarios which failed twice (normal and re-run) are listed twice.

Do you have any setting in your plugin using which this could be avoided?

Cheers!!

**Comment by damianszczepanik** [comment]
I think this is what has been already introduced via https://github.com/damianszczepanik/cucumber-reporting/pull/894 by @dabogee so you can review before it will be published
