### ISSUE TITLE
treatSkippedAsFailed as an Option

### ISSUE THREAD

**Issue by ZeddEn** [damianszczepanik/maven-cucumber-reporting#177]
Hello,

As you already know, the skipped tests are treated as failed and thus sometimes making the report hard to read. Could you please as this option for the skipped tests, as it is already covered for pending and undefined?

// do not make scenario failed when step has status SKIPPED
configuration.setNotFailingStatuses(Collections.singleton(Status.SKIPPED));

Much thanks!

**Comment by damianszczepanik** [comment]
Not sure about your intention

**Comment by ZeddEn** [comment]
Well I just want to have an option to disable putting skipped tests as failing. Something like <setNotFaillingSkipped>false</setNotFaillingSkipped> which would refer to this configuration.setNotFailingStatuses(Collections.singleton(Status.SKIPPED)); on the other plugin. I want to keep using the maven plugin. Thanks.

**Comment by damianszczepanik** [comment]
The code which you are referring to is dependency for this plugin so you can use it

**Comment by ZeddEn** [comment]
Is there a way to use directly from the POM? As I want to keep using the Maven plugin and not the Jenkins one? 
THanks

**Comment by damianszczepanik** [comment]
Should be supported by https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/CucumberReportGeneratorMojo.java but if not you can add support for this and I will be happy to merge it

**Comment by ZeddEn** [comment]
Yes I have added the support. Here is the PR: https://github.com/damianszczepanik/maven-cucumber-reporting/pull/178
Thanks in advance

**Comment by damianszczepanik** [comment]
Great, will release new version

**Comment by ZeddEn** [comment]
Hello, you have an idea when is the new release going to be?
Thanks.

**Comment by damianszczepanik** [comment]
Now https://github.com/damianszczepanik/maven-cucumber-reporting/releases
