### ISSUE TITLE
Version 5.3.0 in maven central lacks  plugin.xml inside

### ISSUE THREAD

**Issue by ko5tik** [damianszczepanik/maven-cucumber-reporting#183]
Hi Daman,

Packaging in pom.xml is set to default jar,   and that's why error is coming:
 
[ERROR] Failed to parse plugin descriptor for net.masterthought:cucumber-reporting:5.3.0 (/home/jenkins/.m2/repository/net/masterthought/cucumber-reporting/5.3.0/cucumber-reporting-5.3.0.jar): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1]

Could you please deploy 5.3.1 ?

**Comment by damianszczepanik** [comment]
Releasing process hasn't been changed from while.
How did you get this error?
Are you having same problem with older versions of the plugin?

**Comment by vrnvorona** [comment]
You need to use maven-cucumber-reporting instead of cucumber-reporting, at least that was issue for me.

**Comment by damianszczepanik** [comment]
True
