### ISSUE TITLE
Report generation in spite of build failure

### ISSUE THREAD

**Issue by rasikaj** [damianszczepanik/maven-cucumber-reporting#19]
I want to generate the cucumber reports even if the build fails. I should be able to see which tests failed in feature-overview.html.
For this if we remove the line in the code 
if (!buildResult) {
                throw new MojoExecutionException("BUILD FAILED - Check Report For Details");
report gets generated even if build failed. 

Can you please release a new version with this change? I am currently using this plugin and it would be truly helpful if you can release a new version with this fix. 

rasikaj.

**Comment by dkirrane** [comment]
+1

**Comment by woodybrood** [comment]
An option is best. I know that I really want to see the report if there are failed tests.

**Comment by damianszczepanik** [comment]
Check last release
