### ISSUE TITLE
Not considering about failing scenarios or features

### ISSUE THREAD

**Issue by deivydasp** [damianszczepanik/maven-cucumber-reporting#200]
Hi @damianszczepanik , noticed one problem with plugin. Build result is not changed to "Failed" when Before/After hooks fails. This situation happens because if statement, which determine when to fail the build, not taking into account failed scenarios/features.

Before:
![image](https://user-images.githubusercontent.com/70365954/136042610-def5fff4-5dd6-4cea-9a9c-5bb125b1104b.png)
After:
![image](https://user-images.githubusercontent.com/70365954/136045555-091ee5ee-5f81-42a9-a03a-0b3b3673f287.png)
In both cases Build was successful, maybe there is an option to fix that?

**Comment by damianszczepanik** [comment]
I believe you can tune your results https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/CucumberReportGeneratorMojo.java#L224

**Comment by goodish452** [comment]
One other case where the build is not marked as failed is when the step is undefined. Not sure if this condition belongs in its own bug or not, but thought I would mention it here in case deivydasp wants to include it in the values being added.
