### ISSUE TITLE
Include an open source license

### ISSUE THREAD

**Issue by mzoffi** [damianszczepanik/maven-cucumber-reporting#204]
Hi,
Could you include an open source license in this project?

**Comment by damianszczepanik** [comment]
Is https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/pom.xml#L47 what you are talking about ?

**Comment by mzoffi** [comment]
Thanks this resovles my issue!
I would suggest that you add an licencse file as well, so that the licence is also shown directly on the projects page.
