### ISSUE TITLE
Unbale to generate html report

### ISSUE THREAD

**Issue by fayaz0062** [damianszczepanik/maven-cucumber-reporting#208]
Following folders are generated instead of html report.
1. generated-sources.
2. generated-test-sources

Please help.

**Comment by damianszczepanik** [comment]
Did you check readme file

**Comment by fayaz0062** [comment]
Are expecting readme file under target file?
No, it is not available under the target file.

**Comment by fayaz0062** [comment]
Hi , Issue resolved on updating the project.

Thanks!
