### ISSUE TITLE
Create mailable file for overview-features.html

### ISSUE THREAD

**Issue by shivam1397a** [damianszczepanik/maven-cucumber-reporting#209]
I want to setup a process through GitHub actions where the generated report is sent to email accounts for better visibility throughout my organisation. Currently when I send the overview-features.html or any other html file generated through this plugin,  the file is successfully sent to the email accounts but since we can not include the dependent file(i.e. external CSS, JS. etc. files) with the html file, all the stying does not get copied. It is displayed as html without any formatting.

Is there a way to you guys can create mailable html files with bit of formatting?

**Comment by damianszczepanik** [comment]
You need to archive whole report and then send it again
