### ISSUE TITLE
html report doesn't escape reserved html characters

### ISSUE THREAD

**Issue by dkirrane** [damianszczepanik/maven-cucumber-reporting#21]
The Cucumber html report does display JUnit assert failures correctly.

For example, if a Step fails with this `junit.framework.Assert.assertEquals` failure:
```
junit.framework.ComparisonFailure: expected:<Foo> but was:<Bar>
```

It will show up in the html reprot like this:
```
junit.framework.ComparisonFailure: expected: but was:
```

**Comment by damianszczepanik** [comment]
Fixed in one of the last release
