### ISSUE TITLE
Steps Graph doesn't appear

### ISSUE THREAD

**Issue by dkirrane** [damianszczepanik/maven-cucumber-reporting#22]
The Steps Graph doesn't appear. 
I think it maybe caused by the having too many Features, Scenarios or Steps.

![cucumberreportstepsgraph](https://cloud.githubusercontent.com/assets/1280116/7588206/84142514-f8b3-11e4-9dd6-dc689f1ed77d.png)
.....
![cucumbertotalrun](https://cloud.githubusercontent.com/assets/1280116/7588207/852d8d14-f8b3-11e4-983b-466957a81ea1.png)

**Comment by damianszczepanik** [comment]
Check the most recent release
