### ISSUE TITLE
Cucumber maven <rerunFailingTestsCount>1</rerunFailingTestsCount> does not rerun failed tests and crashes generating pretty cucumber reports

### ISSUE THREAD

**Issue by SeleniumNinja** [damianszczepanik/maven-cucumber-reporting#243]
https://stackoverflow.com/questions/78007835/cucumber-maven-rerunfailingtestscount1-rerunfailingtestscount-does-not-rerun

**Comment by damianszczepanik** [comment]
What if you don't put this flag into configuration? Still failing?

**Comment by SeleniumNinja** [comment]
<rerunFailingTestsCount>1</rerunFailingTestsCount> has to be inside <configuration> - otherwise the code won't compile. So I assume some other dependencies can have influence on this.

**Comment by SeleniumNinja** [comment]
"rerunFailingTestsCount" has to be inside "configuration" tag - otherwise
the code won't compile. So I assume some other dependencies can have
influence on this.

wt., 20 lut 2024 o 23:25 Damian Szczepanik ***@***.***>
napisał(a):

**Comment by SeleniumNinja** [comment]
The issue was not described properly.
