### ISSUE TITLE
Generate Maven Cucumber Report with Tags Excluded

### ISSUE THREAD

**Issue by MikeSurio** [damianszczepanik/maven-cucumber-reporting#268]
Hi, I would like to reduce the space consumed by the html report generated from our test tags. how can I exclude tag on maven configuration. We are supporting about 40 application and growing. We tend to use "@not-this-application" on some Test case that not are applicable to that market and we want those tags to not create report. Here is the current configuration we are using.

> <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>5.8.1</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>Cucumber Report</projectName>
                            
                            <skip>false</skip>
                            
                            <outputDirectory>${project.build.directory}/cucumber-reports-json</outputDirectory>
                            
                            <inputDirectory>${project.build.directory}</inputDirectory>
                            <mergeFeaturesById>true</mergeFeaturesById>
                            
                            <mergeFeaturesWithRetest>true</mergeFeaturesWithRetest>
                            
                            <jsonFiles>
                                
                                <param>**/cucumber.json</param>
                            </jsonFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L199 does it like the solution for your problem ?

**Comment by MikeSurio** [comment]
I was using maven-cucumber-reporting so I was not able to use the configuration.setExcludedTagsFromReport. Is there any documentation that I can follow to use that configuration on the pom.xml?

**Comment by damianszczepanik** [comment]
Fixed in #269 so wait for next release

**Comment by MikeSurio** [comment]
Hi @damianszczepanik, Thank you! It is working on my local test now. will try it on our pipeline
