### ISSUE TITLE
Build not breaking when a scenario fails

### ISSUE THREAD

**Issue by akrourkarim** [damianszczepanik/maven-cucumber-reporting#36]
Hi,

I'm using your maven plugin for acceptance tests purposes. I've configured the plugin so that the state of a scenario that has undefined steps is 'failed'.
```
      ...
      <checkBuildResult>true</checkBuildResult>
      <undefinedFails>true</undefinedFails>
      ...
```
What's nice is that the configuration works fine. Such scenarios are considered as failed in the report :satisfied:

However I'm surprised that the build is passed. :anguished: I was expecting that the maven plugin would have thrown an exception to interrupt the build and it is not the case. Reading the code of this plugin, I've find out that the build is only interrupted when at least one step fails as shown in the following code extract:
```  
            if (checkBuildResult) {
                boolean buildResult = reportBuilder.getBuildStatus();
                if (!buildResult) {
                    throw new MojoExecutionException("BUILD FAILED - Check Report For Details");
                }
            }
```
The method 'getBuildStatus()' returns false if one step is failed.

Now here is my enhancement proposal. 
:bulb: I wonder how possible it is, to enhance this plugin so that it throws the same exception when the scenario is failed something like:
```
            if (checkBuildResult) {
                boolean failedScenarioFlag = reportBuilder.hasFailedScenario();
                if (!failedScenarioFlag) {
                    throw new MojoExecutionException("BUILD FAILED - Check Report For Details");
                }
            }
```
This would have the following advantages:
* The decision whether a build must be interrupted or not is moved out of the report plugin that has for goal to only generate nice reports. Only the maven plugin knows about the concept of buiild. The report builder should only provide information regarding the report.
* Because it is already possible to configure whether a scenario is failed or not, it will be then implicitly possible to configure when a build must be interrupted or not.

:grey_question: Is this minor enhancement meaningful for you?

**Comment by damianszczepanik** [comment]
This solution is deprecated, new one has been released.
