### ISSUE TITLE
Plugin is not compatible with cucumber-reporting version 1.1.0

### ISSUE THREAD

**Issue by sukeshjain** [damianszczepanik/maven-cucumber-reporting#37]
Plugin is not compatible with cucumber-reporting version 1.1.0. It gives error
java.lang.NoSuchMethodError: net.masterthought.cucumber.ReportBuilder.<init>(Ljava/util/List;Ljava/io/File;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZZZZZZLjava/lang/String;ZZ)V

Provided a pull request to fix this problem. Please merge it and release a new version

**Comment by damianszczepanik** [comment]
New releases won't be compatible with first release
