### ISSUE TITLE
Support for multiple json output files

### ISSUE THREAD

**Issue by petmar** [damianszczepanik/maven-cucumber-reporting#4]
Hello,

First of all, thank you very much for the excellent work on the cucumber-reporting. I have just set up a project that uses the mojo, and it works very well.
Do you intend to also add support for multiple json output files in the mojo?

**Comment by cjbooms** [comment]
Will this be released any time soon? I'm very interested in the updated functionality.

**Comment by kingsleyh** [comment]
I’ve been swamped with other stuff recently but I’ll try to release this soon.

—K

**Comment by patelakhil** [comment]
We are also interested in this fix as it will be very helpful for multiple and parallel execution enviornment
