### ISSUE TITLE
Unable to run plugin directly on command line

### ISSUE THREAD

**Issue by jlorenzen** [damianszczepanik/maven-cucumber-reporting#41]
I'm trying to generate the html reports after a failed build but when I run `mvn cucumber-reporting:generate` it doesn't work. Here is the output when running that command:
```
[INFO] --- maven-cucumber-reporting:2.0.0:generate (default-cli) @ everydollar-budget-api ---
[WARNING] /Users/jlorenzen/Development/src/lampo/everydollar-budget-api/${${project.build.directory}/cucumber.json} does not exist.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.462 s
[INFO] Finished at: 2016-03-16T09:42:16-05:00
[INFO] Final Memory: 10M/309M
[INFO] ------------------------------------------------------------------------
```

I have that property defined in the `pom.xml` but when running that command directly in the command line I don't think it picks up those values. So I tried running `mvn cucumber-reporting:generate -DcucumberOutput=target/cucumber.json` I get the same error.

It would be really nice if I could run this goal directory on the command line. Seems like we should be able to define that property on the command line.

**Comment by damianszczepanik** [comment]
I've updated README so you can take a look. One of the problem was that #35 caused regression, second that you used wrong command to build the report. Try to `mvn verify` or update example pom.xml file if you have different flow.

You can use SNAPSHOT version or wait for text release that should be soon.

**Comment by jlorenzen** [comment]
ok thanks. I'll watch for the next release version.
I'm not using the wrong command. What I want to do is build the reports even if the tests fail. So something like `mvn clean verify ; mvn cucumber-reporting:generate`.
If I update the failsafe plugin to continue even if the build fails, I can get `mvn verify` to build the reports but then the build doesn't fail if there were failures (which is worse then not having the reports built).
So if I chain the commands, I can get a broken build if there are failures and get the tests generated.
