### ISSUE TITLE
When tests have failed, this plugin may prevent execution of all the remaining phases

### ISSUE THREAD

**Issue by a-yumashin** [damianszczepanik/maven-cucumber-reporting#45]
You have the following block of code there:

```
if (checkBuildResult) {
    boolean buildResult = reportBuilder.hasBuildPassed();
    if (!buildResult) {
        throw new MojoExecutionException("BUILD FAILED - Check Report For Details");
    }
}
```

By default checkBuildResult is _true_.
I cannot imagine the reason to have this code there. Why a hell should a **reporting** plugin prevent execution of all the remaining phases?! I'm having trouble because of this code - see the very first post in [Plugin prevents next plugins execution when tests failed?](https://github.com/damianszczepanik/cucumber-reporting/issues/503)
Having set checkBuildResult to _false_ I fixed the problem, but... I'm still wondering why anybody may need it to be _true_?! Got a strong desire to remove this whole block of code )

**Comment by damianszczepanik** [comment]
This is plugin for reporting the results, not executing tests

**Comment by cbaldan** [comment]
@damianszczepanik could you make this behavior parameterized?

I imagine the default would be enabled, but it could be overwritten in the _pom_ of the project.

**Comment by damianszczepanik** [comment]
Have you tried this https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/CucumberReportGeneratorMojo.java#L110 ?

**Comment by cbaldan** [comment]
@damianszczepanik I did not know of that parameter, it does add a verification if the report was indeed generated.
But I think what @a-yumashin is really interested is what has been discussed over #61
