### ISSUE TITLE
HTML report not generated for tests running many features

### ISSUE THREAD

**Issue by ualarm** [damianszczepanik/maven-cucumber-reporting#47]
We have smoke test features and regression test features.
Smoke tests executed about 30 minutes and reports were generated.
Regression tests executed about 10 hours and reports were not generated.
Maven command window did not show any meaningful error information.
I executed a couple of regression test features and reports were generated. 
Surefire reports were always generated.
I am wondering what went wrong when reports were not generated? Any configuration I can set to see more information? My current maven for maven-cucumber-reporting plugin is:
<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>2.7.0</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>the-source</projectName>
							<outputDirectory>${project.basedir}/cucumber-html-reports/${report.folder}</outputDirectory>
							<cucumberOutput>${project.build.directory}</cucumberOutput>
							<enableFlashCharts>false</enableFlashCharts>
						</configuration>
					</execution>
				</executions>
</plugin>

**Comment by damianszczepanik** [comment]
Looks like the problem with reporting. Can you attach JSON report? You can reduce confidential data using https://github.com/damianszczepanik/silencio

**Comment by ualarm** [comment]
Thanks for quick response. 
I assume you mean the 'cucumber1.json' file. It was empty (0 KB). Or is there another JSON report? If so, what is the location then? 
I have tried to execute 10 feature files for regression which lasts 1.5 hours and report is generated. Now my workaround is splitting the regression into 10 batches where each batch executes 10 features.

**Comment by damianszczepanik** [comment]
I need the JSON file which you use as the input for the report

**Comment by ualarm** [comment]
The JSON file was empty when report was not generated

**Comment by damianszczepanik** [comment]
If the JSON is empty then you need to find the problem why what is not related to reporting. Reporting uses JSON as input, not output.
