### ISSUE TITLE
report-feature html files have too long names and would not open

### ISSUE THREAD

**Issue by airyz** [damianszczepanik/maven-cucumber-reporting#53]
Thanks for this report.  I have an issue with the report-feature html files.  

The html filename is too long (is using the filepath as pattern) and this causes it not opening (at least in Windows).

Example of filenames:
report-feature_C--Users-eraclis-Documents-Projects-SpringBootExample-spring-boot-testing-src-test-resources-features-author-feature_6.html

**Comment by damianszczepanik** [comment]
Name of the feature is based on the feature ID which is created according to the feature name so my suggestion is to shorten the feature name and add description with details.

**Comment by airyz** [comment]
@damianszczepanik Thanks for your response.  The name of the feature example above can't get any shorter.  It's author.feature.  The long part is the path that is using in the html name.

**Comment by damianszczepanik** [comment]
Windows has limitation for path length while Linux also has it but its much, much longer.

I don't have a plan for supporting this in near future.

**Comment by djangofan** [comment]
I just tried this as a Maven task and it generates all the html but doesn't generate a standard  'index.html' .  Why?

**Comment by shash431** [comment]
hi,
   Report is not getting generated for all the tags executed and the report has oly the recent tag executed and from my view the plugin should support parallel plugins like teymers etc.,
below is the pom.xml  :   


<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>CucumberDeviceParallel</groupId>
	<artifactId>cucumber-Device-parallel</artifactId>
	
	<packaging>jar</packaging>
	<version>5.0-SNAPSHOT</version>
	<name>my-app</name>
	<url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<cucumber.version>1.2.5</cucumber.version>
		<junit.version>4.12</junit.version>
		<springframework.version>4.1.3.RELEASE</springframework.version>
		<org.slf4j.version>1.7.7</org.slf4j.version>
		<extentreports.version>3.0.6</extentreports.version>
		<test.integration.pattern>**/*IntegrationTest*.java</test.integration.pattern>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.build.resourceEncoding>UTF-8</project.build.resourceEncoding>
		<maven.compile.encoding>UTF-8</maven.compile.encoding>

		
		<log4j.version>2.8.2</log4j.version>
		<powermock.version>1.7.0</powermock.version>

	</properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>3.12.0</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-core</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.3.5</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-shade-plugin</artifactId>
			<version>2.3</version>

		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>gherkin</artifactId>
			<version>4.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>4.1.2</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpmime</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.53.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.codoid.products</groupId>
			<artifactId>fillo</artifactId>
			<version>1.14</version>
		</dependency>
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>${extentreports.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-htmlunit-driver</artifactId>
			<version>2.48.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.vimalselvam</groupId>
			<artifactId>cucumber-extentsreport</artifactId>
			<version>3.0.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>javax.mail</artifactId>
			<version>1.5.0</version>

		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.7</version>

		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>2.53.1</version>
		</dependency>
		<dependency>
			<groupId>com.github.temyers</groupId>
			<artifactId>cucumber-jvm-parallel-plugin</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.1.5</version>

		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>${cucumber.version}</version>

		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>

		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-spring</artifactId>
			<version>${cucumber.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<version>${springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>${springframework.version}</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.8.8</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
		
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.3.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>3.12.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<version>2.53.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.3.1</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-chrome-driver</artifactId>
			<version>2.53.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<version>2.53.1</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.3.5</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-htmlunit-driver</artifactId>
			<version>2.48.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-ie-driver</artifactId>
			<version>2.53.1</version>
		</dependency>
		
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>maven-cucumber-reporting</artifactId>
			<version>3.12.0</version>
		</dependency>
        <dependency>
        <groupId>net.masterthought</groupId>
				<artifactId>cucumber-sandwich</artifactId>
				<version>3.12.0</version></dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>16.0.1</version>
		</dependency>
		<dependency>
			<groupId>net.thucydides</groupId>
			<artifactId>thucydides-junit</artifactId>
			<version>0.4.9</version>
		</dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.6.1</version>
			<type>pom</type>
		</dependency>

	</dependencies>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>

		
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
					<includes>
						<exclude>**/*BDDTest.java</exclude>
					</includes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>0.0.5</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>cucumber-jvm-example</projectName>
							<outputDirectory>${project.build.directory}/site/cucumber-reports</outputDirectory>
							<cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
							<enableFlashCharts>false</enableFlashCharts>
							<skippedFails>true</skippedFails>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<additionalClasspathElements>
						<additionalClasspathElement>resources</additionalClasspathElement>
					</additionalClasspathElements>
					<forkCount>2</forkCount>
					<reuseForks>true</reuseForks>
					<includes>
						<include>**/*IT.java</include>
					</includes>
					<runOrder>alphabetical</runOrder>
					<argLine>-Duser.language=en</argLine>
					<argLine>-Xmx512m</argLine>
					<argLine>-XX:MaxPermSize=256m</argLine>
					<argLine>-Dfile.encoding=UTF-8</argLine>
					<encoding>UTF-8</encoding>
					<systemPropertyVariables>
						
					</systemPropertyVariables>
				</configuration>
				<executions>
					<execution>
						<id>failsafe-integration-test</id>
						<phase>integration-test</phase>
						<goals>
							<goal>integration-test</goal>
						</goals>

					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>4.2.0</version>
				<executions>
					<execution>
						<id>generateRunners</id>
						<phase>validate</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							
							<glue>
								<package>com.cucumber.stepdefinitions</package>
							</glue>
							<strict>true</strict>
							<monochrome>true</monochrome>
							
							<outputDirectory>
								${project.build.directory}/generated-test-sources/cucumber
							</outputDirectory>
							<featuresDirectory>
								src/test/resources/features/
							</featuresDirectory>
							<cucumberOutputDir>target/cucumber-reports</cucumberOutputDir>
							<format>json</format>
							<format>html</format>
							<encoding>UTF-8</encoding>
							<tags>
								<tag>${TestType}</tag>
							</tags>
                            <tags>
								~@ignore
							</tags>
							<customVmTemplate>
								src/main/resources/cucumber-custom-runner.vm
								
							</customVmTemplate>
							
							<namingScheme>pattern</namingScheme>
							<namingPattern>{f}_{c}IT</namingPattern>
							<plugins>
								<plugin>
									<name>com.cucumber.listener.ExtentCucumberFormatter</name>
									<extension>html</extension>
									<outputDirectory>output/</outputDirectory>
								</plugin>
							</plugins>
							<parallelScheme>SCENARIO</parallelScheme>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.7</version>
				<executions>
					<execution>
						<id>copy-resources</id>
						
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>target/test-classes/com/yourcompany/saucecucumberjvm</outputDirectory>
							<resources>
								<resource>
									<directory>src/test/resources</directory>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>1.8</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>steps/</source>
								<source>src/test/java/</source>
								<encoding>UTF-8</encoding>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>net.thucydides.maven.plugins</groupId>
				<artifactId>maven-thucydides-plugin</artifactId>
				<version>0.9.275</version>
				<executions>
					<execution>
						<id>thucydides-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.20</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>3.12.0</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>CucumberBDD - Example</projectName>
							<outputDirectory>${project.build.directory}/site/cucumber_Test_reports</outputDirectory>
							<cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
							<parallelTesting>true</parallelTesting>
							<checkBuildResult>true</checkBuildResult>
							
							<buildNumber>42</buildNumber>
						</configuration>
					</execution>
				</executions>
			</plugin>
			</plugins>
	</build>
	<reporting>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>2.17</version>
				<configuration>
					<configLocation>${basedir}/google-style.xml</configLocation>
					<encoding>UTF-8</encoding>
					<linkXRef>false</linkXRef>
					<consoleOutput>true</consoleOutput>
					<failsOnError>false</failsOnError>
					<includeTestSourceDirectory>true</includeTestSourceDirectory>
					<excludes>**/options/*.java</excludes>
				</configuration>
				<reportSets>
					<reportSet>
						<reports>
							<report>checkstyle</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jxr-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<aggregate>true</aggregate>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>cobertura-maven-plugin</artifactId>
				<version>2.7</version>
				<configuration>
					<formats>
						<format>html</format>
						<format>xml</format>
					</formats>
				</configuration>
				<reportSets>
					<reportSet>
						<reports>
							<report>cobertura</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>findbugs-maven-plugin</artifactId>
				<version>3.0.3</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-pmd-plugin</artifactId>
				<version>3.6</version>
				<configuration>
					<excludes>
						
						<exclude>**/RuntimeOptions.java</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</reporting>
</project>



please check and let if something is going wrong with my pom.xml  or else let me know how to get all the reports genareted and should be able to view in the consolidated report.

**Comment by damianszczepanik** [comment]
Honestly I have no plan to support it as this will break compatibility with older version. I believe you can make the ID/URL shorten.

**Comment by hi-Kedarnath** [comment]
When multiple feature files were run, only able to view one report in browser as path/location of other report files (.html) are stored in symbol-ink.
Example - I ran 3 feature files and the html created as below. Also mentioned the location stored for each file.
File Name - report-feature_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_1-feature.html
Location of File - F:\eclipse-dsl-luna-SR2-win32-x86_64\parallel_feature\artifacts\12Nov2018-120327PM-UTC\report-12Nov2018-120327PM-UTC\cucumber-html-reports

File Name - report-feature_2_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_3-feature.html
Location of File - F:\ECLIPS~1\PARALL~1\ARTIFA~1\123CD8~1\REPORT~1\CUCUMB~1

File Name - report-feature_1_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_2-feature.html
Location of File - F:\ECLIPS~1\PARALL~1\ARTIFA~1\123CD8~1\REPORT~1\CUCUMB~1

As the location are stored as symbol-link so feature file 2 and 3 can not be opened from browser as it expect path like 
file:///F:/eclipse-dsl-luna-SR2-win32-x86_64/parallel_feature/artifacts/12Nov2018-120327PM-UTC/report-12Nov2018-120327PM-UTC/cucumber-html-reports/report-feature_1_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_2-feature.html

file:///F:/eclipse-dsl-luna-SR2-win32-x86_64/parallel_feature/artifacts/12Nov2018-120327PM-UTC/report-12Nov2018-120327PM-UTC/cucumber-html-reports/report-feature_2_F--eclipse-dsl-luna-SR2-win32-x86_64-parallel_feature-src-test-resources-com-parallel_run_3-feature.html

Is this due to some configuration issue from my end or it has something to do with existing code. Please let me know.

**Comment by damianszczepanik** [comment]
Will be supported with one of the next version

**Comment by damianszczepanik** [comment]
Support for this problem will be delivered with next release.

**Comment by kezebag** [comment]
Hi @damianszczepanik, what release is this change in? I've just tried the latest 4.3 and still see the issue.... Here's the stacktrace:
net.masterthought.cucumber.ValidationException: java.io.FileNotFoundException: …feature.html (File name too long)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:80)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:59)
	at net.masterthought.cucumber.ReportBuilder.generatePages(ReportBuilder.java:154)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:98)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:323)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:247)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1819)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

**Comment by damianszczepanik** [comment]
As I wrote: next release
