### ISSUE TITLE
Generate reports when  <testFailureIgnore>true</testFailureIgnore> is set to false

### ISSUE THREAD

**Issue by airyz** [damianszczepanik/maven-cucumber-reporting#54]
The problem:
When I use <testFailureIgnore>true</testFailureIgnore> as suggested in README then I get the report but the BUILD is successful on CI even when the scenarios fail.

On the other hand if we use <testFailureIgnore>false</testFailureIgnore> then reports are not created at all.

Is there any suggested solution?

**Comment by damianszczepanik** [comment]
Looks like this flag is not supported any more and the README file was not updated....

The approach for setting build failed or passed has been changed recently and maybe it is not fully supported by maven plugin

**Comment by damianszczepanik** [comment]
README is updated now, flag is not supported any more

**Comment by airyz** [comment]
@damianszczepanik Any suggested solution though for this?  Without that flag the reports are not generated if the Build failed.

**Comment by damianszczepanik** [comment]
If the report is not generated it means that you passed wrong path with jcon report. I could generate the report

**Comment by shohilbagdai** [comment]
Hey Airyz.
I am facing the same issue, is it working for u now?
if yes pls let me know how

**Comment by cbaldan** [comment]
@airyz @shohilbagdai seems the solution would be using the maven **failsafe** plugin.
Take a look at #61
