### ISSUE TITLE
Classifications

### ISSUE THREAD

**Issue by KLBonn** [damianszczepanik/maven-cucumber-reporting#58]
Hi Damian,

thanks for sharing the cucumber reporting engine!

I also like the new classifications you recently introduced in cucumber-reporting.
Can you make them accessible / usable in the maven mojo?
Maybe simply as another configuration attribute <classifications> containing a collection of <classification> elements or directly a comma-separated list of classification strings.

We typically have different maven profiles for different test setups, so this could play together nicely.

**Comment by damianszczepanik** [comment]
Would you like to prepare PR for this? I will be happy to merge it

**Comment by KLBonn** [comment]
OK, see [here](https://github.com/damianszczepanik/maven-cucumber-reporting/pull/59) -- what do you think about it?
