### ISSUE TITLE
Report accepts jsons only from one directory

### ISSUE THREAD

**Issue by jjadotP** [damianszczepanik/maven-cucumber-reporting#65]
Hello,

I try with this plugin to generate one report for multiple json files.
The problem is the tag cucumberOutput must be one file and is take only one times.

So when we have more than one test the html report contains always only one test report.
I use the plugin like :
`<plugin>
  <groupId>net.masterthought</groupId>
  <artifactId>maven-cucumber-reporting</artifactId>
  <executions>
    <execution>
      <id>execution</id>
      <phase>verify</phase>
      <goals>
        <goal>generate</goal>
      </goals>
      <configuration>
        <projectName>behavior</projectName>
        <outputDirectory>${project.build.directory}/cucumber-html-reports</outputDirectory>
        <cucumberOutput>${project.build.directory}/cucumber/cucumber1.json</cucumberOutput>
        
        <enableFlashCharts>false</enableFlashCharts>
      </configuration>
    </execution>
  </executions>
</plugin>`

The first test is configure like this :
`@CucumberOptions(
    features = { "src/test/resources/feature/Feature1.feature" },
    plugin = { "pretty:target/cucumber1.log", "html:target/cucumber", "json:target/cucumber/cucumber1.json" })`
The second test is configure like this :
`@CucumberOptions(
    features = { "src/test/resources/feature/Feature2.feature" },
    plugin = { "pretty:target/cucumber2.log", "html:target/cucumber", "json:target/cucumber/cucumber2.json" })`

Thanks

**Comment by damianszczepanik** [comment]
Upgrade the plugin

**Comment by jjadotP** [comment]
Hello,

I don't understand your responds between the version 3.4.0 what I use and the version 3.7.0 what I try now, the difference is in the cucumber reporting version.

I see the possibility for the cucumber reporting to manage more than one files. It works.

For me the problem is more in the class CucumberReportGeneratorMojo wich take only one cucumber output file : `private File cucumberOutput;`
Or it is my pom which is not correctly write but if it is this case, it is possible to have more explanation?

Thanks

**Comment by damianszczepanik** [comment]
The configuration you provided eh enableFlashCharts is not valid any more and says you have very old cucumber version.

**Comment by jjadotP** [comment]
When I say in my previous post the cucumber reporting, I want says the maven cucumber reporting.
So now I have yet the same problem with the version 3.7.0 of the maven cucumber reporting.
To solve the problem I do that but with this solution I have two different report.

<plugin>
	<groupId>net.masterthought</groupId>
	<artifactId>maven-cucumber-reporting</artifactId>
	<executions>
		<execution>
			<id>execution1</id>
			<phase>verify</phase>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<projectName>behavior</projectName>
				<outputDirectory>${project.build.directory}/cucumber1-reports</outputDirectory>
				<cucumberOutput>${project.build.directory}/cucumber/cucumber1.json</cucumberOutput>
			</configuration>
		</execution>
		<execution>
			<id>execution2</id>
			<phase>verify</phase>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<projectName>behavior</projectName>
				<outputDirectory>${project.build.directory}/cucumber2-reports</outputDirectory>
				<cucumberOutput>${project.build.directory}/cucumber/cucumbe2.json</cucumberOutput>
			</configuration>
		</execution>
	</executions>
</plugin>

**Comment by damianszczepanik** [comment]
Yes, looks like https://github.com/damianszczepanik/maven-cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/CucumberReportGeneratorMojo.java#L47 could be extended and takes the list instead of single directory. Would you prepare pull request for this so I will accept it?

**Comment by damianszczepanik** [comment]
Fixed
