### ISSUE TITLE
Is Embedding Text reporting feature is supported by mojo

### ISSUE THREAD

**Issue by mkhare75** [damianszczepanik/maven-cucumber-reporting#7]
Hello 

I tried out "Embedding Text" & "Embedding Screenshot" features of cucumber (http://cukes.info/reports.html) with this reporting plugin.

 Embedding Screenshot seems to be working file but "Embedding Text" output are not getting included in generated reports. 

I can see the corresponding statetment in test generated json file though (which mojo is reading to generate reports).

Just wondering this is supported or not or whether I'm doing something wrong ?

**Comment by damianszczepanik** [comment]
If you still need support for this, open request at https://github.com/damianszczepanik/cucumber-reporting
