### ISSUE TITLE
Report is not generated when tests fail

### ISSUE THREAD

**Issue by pnakhat** [damianszczepanik/maven-cucumber-reporting#70]
When test fails reports are not generated. It complains on surefire  plugin

**Comment by damianszczepanik** [comment]
More details please

**Comment by grmendes** [comment]
The report is not generated because surefire plugin is not configured to ignore failures. Configuring the surefire plugin as below fixes your problem @pnakhat .
`<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <testFailureIgnore>true</testFailureIgnore>
    </configuration>
</plugin>`

But this configuration causes the build to never break, even when there are test failures. I'm submitting a pull request to this issue that properly breaks the build when there are test failures, also fixing README.md to show the above configuration.

**Comment by mechingineer** [comment]
When can we expect a roll out for this ?

**Comment by damianszczepanik** [comment]
Already done

**Comment by aistoica** [comment]
I found the solution for this. Use failsafe plugin:
> 
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>3.15.0</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>Tests</projectName>
                            <outputDirectory>target/cucumber-reports/advanced-reports</outputDirectory>
                            <cucumberOutput>target/cucumber-reports/CucumberTestReport.json</cucumberOutput>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
> 

Hope it helps

**Comment by geekyPiyush** [comment]
Hey @grmendes  and @damianszczepanik . Will the build break with above configuration for Allure reports too?
