### ISSUE TITLE
Multiple jsonFiles Directory

### ISSUE THREAD

**Issue by trevor-winters** [damianszczepanik/maven-cucumber-reporting#73]
I am trying to configure multiple jsonFiles. Is there a way to just specify a directory instead of naming out each json file?

Current Implementation:
```
<configuration>
    <projectName>${project.name}</projectName>
    <outputDirectory>${project.build.directory}</outputDirectory>
    <jsonFiles>
        <param>${project.build.directory}/cucumber-report-1.json</param>
        <param>${project.build.directory}/cucumber-report-2.json</param>
        <param>${project.build.directory}/cucumber-report-3.json</param>
        <param>${project.build.directory}/cucumber-report-4.json</param>
    </jsonFiles>
</configuration>
```

I wanted something like this:
```
<jsonFiles>
    <param>${project.build.directory}</param>
</jsonFiles>
```

Where I only need to specify a directory. 
Thanks!

**Comment by trevor-winters** [comment]
It looks like I'm able to use cucumberOutput with a directory.

**Comment by mechingineer** [comment]
@trevor-winters Hi, Could you please tell me how you managed to give just a directory in pom.xml and not the exact json files?

In my case, I have a parallel execution creating unknown number of jsons in a directory. Now I want this plugin to pick all the JSONS from that directory.

Could you please help me in achieving that?
