### ISSUE TITLE
How can I configure report to retain line feeds in my comments in the .feature file?

### ISSUE THREAD

**Issue by djangofan** [damianszczepanik/maven-cucumber-reporting#78]
How can I configure report to retain line feeds in my comments in the .feature file?

Right now the entire text of the Feature:  comments in my .feature files  are displayed on the html report with all the line-feeds removed.   I can't seem to get around this.   Is there a secret to retaining the line feeds?  I want my HTML test report to retain text formatting from the .feature file.

For example, I want this bulleted list to show on the report just like you see here, without being concatenated to one line:

```
# whatever.feature

Feature:  just to show my point
  Business Rules:
    1. Rule 1
    2. Rule 2
    3. Rule 3

    Scenario:  ....
```

**Comment by damianszczepanik** [comment]
Can you share JSON file as I'm not sure what information is missing in the report. I though about comment but I think this is not what you need.

**Comment by djangofan** [comment]
I can't give you JSON because of privacy issue but I can show you this screenshot: 
<img width="596" alt="screen shot 2017-11-11 at 11 06 50 am" src="https://user-images.githubusercontent.com/810894/32692645-969db95a-c6d0-11e7-9625-13ebf3dd654c.png">

**Comment by damianszczepanik** [comment]
And what is what what do you expect?

**Comment by austenjt** [comment]
Just like what I said above: "without being concatenated to one line,  preserving line feeds from .feature file"

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json#L275 it works fine so provide JSON so I can reproduce it. You can [anonymize JSON](https://github.com/damianszczepanik/silencio) to hide private data.

**Comment by djangofan** [comment]
Well, i can tell you that yes, in the cucumber.json file that is generated from my tests, in the "description" field (under each feature),  the string has '\n'  characters in those places where i am expecting to see a line feed, and YET, on the HTML report, the line feeds do not show up.   This occurs only on the Jenkins version of the generated report, from the Jenkins cuke report plugin.     To clarify, I don't see this bug when generating the report from my local Maven build.   maybe i am asking for help on this in the wrong project?

**Comment by damianszczepanik** [comment]
Having no JSON I'm not able to reproduce and help

**Comment by djangofan** [comment]
I appreciate the help. Glad I have a lead on chasing the issue.
