### ISSUE TITLE
Configure report to take the folder of JSON as input and not the name of the individual JSON files

### ISSUE THREAD

**Issue by mechingineer** [damianszczepanik/maven-cucumber-reporting#79]
Hi,

Please add support for passing the JSON directory as a parameter in the pom.xml instead of passing the JSON files individually.

For example:
"""
<plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>3.12.0</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>cucumber-jvm-example</projectName>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            
                            <cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
                            <jsonFiles>
                                **<param>${project.build.directory}/target/cucumber-parallel/</param>**
                            </jsonFiles>                                <parallelTesting>false</parallelTesting>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
"""

In the highlighted portion, I have mentioned a directory containing list of JSON files but it doesn't take the JSONs inside the folder in consideration. Please help me in getting this resolved.

**Comment by AndyGee** [comment]
This seems to already be available in the current release?

I add this to @CucumberOptions on a test class:
format = {"json:target/json-report/MyClassReport.json"}

And this is the plugin config:
<cucumberOutput>${project.build.directory}/json-report/</cucumberOutput>

All the json reports pushed to that directory are evaluated by the generated report.

So for me this is working. Maybe some issue is arising during parallel execution?

**Comment by kathyrollo** [comment]
@mechingineer This can already be achieved by using wildcards:
~~~
<jsonFiles>
	<param>**/my-json-files/*.json</param>
</jsonFiles>
~~~
Requesting OP to close issue. Thanks!
