### ISSUE TITLE
Ignore missing json files when selectively running tests

### ISSUE THREAD

**Issue by AndyGee** [damianszczepanik/maven-cucumber-reporting#80]
I have a bunch of tests that create json files. It is often useful to just run one or two tests/scenarios:

mvn clean verify -Dtest=LoginTest,AccountsTest

The report is configured to parse multiple files:

<jsonFiles>
  <param>${project.build.directory}/json-report/Login.json</param>
  <param>${project.build.directory}/json-report/Accounts.json</param>
  <param>${project.build.directory}/json-report/AccountSources.json</param>
....

The AccountSources.json is not generated, and so the report fails with a java.io.FileNotFoundException.

The report should not fail on missing files, rather only warn.

**Comment by damianszczepanik** [comment]
Well, if you set two files than the report expect two. I'm rather for creating flag failOnMissing or similar

**Comment by AndyGee** [comment]
If submitted a patch for the maven plugin that would resolve this. Rather than passing the report missing files, just filter them in the plugin. Wdyt?

**Comment by damianszczepanik** [comment]
The solution should go first to https://github.com/damianszczepanik/cucumber-reporting and I would like to accept it once it will bee provided
