### ISSUE TITLE
Compatibility with cucumber report 2.3.1

### ISSUE THREAD

**Issue by jontxo** [damianszczepanik/maven-cucumber-reporting#87]
hello

Is the plugin compatible with the report generated with the new version of cucumber ?

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>2.3.1</version>
</dependency>

I ask because I am getting the following error:
 Failed to execute goal net.masterthought:maven-cucumber-reporting:3.14.0:generate (execution) on project reportgeneration: Error Found:: BUILD FAILED - Check Report For Details -> [Help 1]

when I use the verify goal of maven. 

Regards

**Comment by damianszczepanik** [comment]
Report should be generated but AFAIK duration will be wrong as new cucumber uses seconds while old one ms

**Comment by jontxo** [comment]
ok, thanks
