### ISSUE TITLE
Html files are duplicated since 3.11 version

### ISSUE THREAD

**Issue by Lenence** [damianszczepanik/maven-cucumber-reporting#91]
Hi,

On my project, if I try to update from 3.10.0 version to another version, html file of each feature is duplicated :
![duplicated_html_files](https://user-images.githubusercontent.com/25954101/37464606-1b20d042-2859-11e8-8138-e4dfdc0c4362.png)

In cucumber.json file, each feature appears only once.
[cucumber.zip](https://github.com/damianszczepanik/maven-cucumber-reporting/files/1815419/cucumber.zip)

Here is my Maven configuration :
`            <plugin>
<groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>${cucumber.reporting.version}</version>
                <executions>
                    <execution>
                        <id>cucumber-report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <jsonFiles>
                                <param>${project.build.directory}/cucumber.json</param>
                            </jsonFiles>
                            <parallelTesting>true</parallelTesting>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

Where am I wrong ?

Thank you for your help.

**Comment by damianszczepanik** [comment]
Could not reproduce it. Probably JSONs are taken twice so check the pattern that decides what files are taken into the report
