### ISSUE TITLE
Embed screenshot per step in HTML report

### ISSUE THREAD

**Issue by kathyrollo** [damianszczepanik/maven-cucumber-reporting#92]
Hi Damian,

Thank you for this wonderful Maven plugin.

Is it possible to embed a screenshot for every step in the generated HTML report? Probably in another column in the Steps tab with a clickable thumbnail (e.g. before Occurrences column).

![overview_steps](https://user-images.githubusercontent.com/28589393/37860528-268db444-2f62-11e8-90e7-8a9be6ea4881.PNG)

**Comment by damianszczepanik** [comment]
EAch step can have more than one occurrences - how would you decide which one should be used?

**Comment by kathyrollo** [comment]
Fair point. How about just embedding a screencap for a failing step in the Failures tab?

**Comment by damianszczepanik** [comment]
You can always attach screenshot to the report and this is possible even now.
