### ISSUE TITLE
Steps list expanding is not working due to custom Content Security Policy restriction on a font file

### ISSUE THREAD

**Issue by azaanant** [damianszczepanik/maven-cucumber-reporting#93]
Expanding option is not working because fontawesome-webfont.woff loading has been blocked by custom security policy.
<img width="2502" alt="screen shot 2018-03-28 at 9 57 05 am" src="https://user-images.githubusercontent.com/37862490/38014417-655529f2-3271-11e8-95f7-2339313e438c.png">

I need to disable the following check to avoid the violation.
<img width="534" alt="screen shot 2018-03-28 at 9 56 28 am" src="https://user-images.githubusercontent.com/37862490/38014406-5b64f576-3271-11e8-80b6-e3912b695179.png">

Could you please get rid of using a custom font for expand/collapse icons?

**Comment by damianszczepanik** [comment]
Upgrade the plugin

**Comment by muralinadadhur** [comment]
Is 3.15.1 the latest version?

**Comment by dabogee** [comment]
> Upgrade the plugin

Hi!
It is a report of the plugin with the latest available version 3.15.0 for now

**Comment by damianszczepanik** [comment]
Could not reproduce, update the plugin and check Jenkins configuration
