### ISSUE TITLE
Section with Browser/Platform/Branch name couldn't be configured for plugin version of report

### ISSUE THREAD

**Issue by ypechenko** [damianszczepanik/maven-cucumber-reporting#97]
I cannot configure Maven-cucumber-reporting plugin in order to display the section with Browser/Platform/Branch name
[Screenshot for this section](https://screenpresso.com/=1YFEd)
It's evident that the section could be configured 

configuration.addClassifications("Platform", "Windows");
configuration.addClassifications("Browser", "Firefox");
configuration.addClassifications("Branch", "release/1.0");

while using cucumber-reporting as dependency but not with the plugin for now?

Is there any way to do it or to fix it?
Thanks

**Comment by damianszczepanik** [comment]
Is supported now
